SQL 1 exercise
NoyRobinson/hibob-academy pull request #8
Opened 2024-09-08 12:32 UTC by NoyRobinson

SQL 1 exercise

2024-09-09 19:10 UTC, mayhuberman requested changes
👑

2024-09-09 19:10 UTC, mayhuberman commented on src/main/resources/db/migration/V202409081400__create-owner.sql
> +CREATE INDEX idx_owner_company_id ON owner(company_id);
create one index for both

2024-09-09 19:10 UTC, mayhuberman commented on src/main/resources/db/migration/V202409081401__create-pet.sql
> +    date_of_arrival DATE
you can add here default value

2024-09-09 19:10 UTC, mayhuberman commented on src/main/resources/db/migration/V202409081400__create-owner.sql
> +CREATE TABLE owner
the migration file name should be separated with '_' and not '-'

2024-09-09 19:10 UTC, mayhuberman commented on src/main/resources/db/migration/V202409081401__create-pet.sql
> +CREATE TABLE pets
the migration file name should be separated with '_' and not '-'

2024-09-09 19:10 UTC, mayhuberman commented on src/main/resources/db/migration/V202409081401__create-pet.sql
> +-- SELECT * FROM pets WHERE date_of_arrival < '2023-09-08';
this is not the query - Get the pets that arrived more than a year ago
this query brings all pets that arrived before '09-08-2023'

2024-09-09 19:10 UTC, mayhuberman commented on src/main/resources/db/migration/V202409081401__create-pet.sql
> +-- SELECT * FROM pets WHERE type = 'dog'
you can use distinct

2024-09-10 08:31 UTC, mayhuberman commented on src/main/resources/db/migration/V202409081400__create_owner.sql
> +CREATE INDEX idx_owner ON owner(company_id, employee_id);
add the fields names to the index name

2024-09-10 08:31 UTC, mayhuberman commented on src/main/resources/db/migration/V202409081400__create_owner.sql
> +    company_id UUID,
company_id in bob is bigint

2024-09-10 08:31 UTC, mayhuberman commented on src/main/resources/db/migration/V202409081400__create_owner.sql
> +    employee_id UUID
employee_id in bob is string

2024-09-10 08:31 UTC, mayhuberman commented on src/main/resources/db/migration/V202409081401__create_pet.sql
> +    company_id UUID,
company_id in bob is bigint

2024-09-10 08:37 UTC, mayhuberman commented on src/main/resources/db/migration/V202409081401__create_pet.sql
> +CREATE TABLE pets
By the way, it's better to be consistent, and the name should be 'pet' in the singular

2024-09-10 13:23 UTC, mayhuberman commented on src/main/resources/db/migration/V202409081400__create_owner.sql
> +    company_id BIGINT,
missing not null

2024-09-10 13:23 UTC, mayhuberman commented on src/main/resources/db/migration/V202409081400__create_owner.sql
> +    employee_id String
should be varchar and missing not null

2024-09-10 13:23 UTC, mayhuberman commented on src/main/resources/db/migration/V202409081401__create_pet.sql
> +    company_id BIGINT,
should be not null

2024-09-10 13:23 UTC, mayhuberman commented on src/main/resources/db/migration/V202409081400__create_owner.sql
> +    company_id BIGINT,
think what other fields shouldn't hold null values

2024-09-10 14:36 UTC, mayhuberman commented on src/main/resources/db/migration/V202409081401__create_pet.sql
> +CREATE INDEX idx_pets_company_id ON pets(company_id);
it wont work because you renamed the table to pet

2024-09-10 14:39 UTC, NoyRobinson commented on src/main/resources/db/migration/V202409081401__create_pet.sql
> +CREATE INDEX idx_pets_company_id ON pets(company_id);
you're right, I'll change it

2024-09-10 15:10 UTC, mayhuberman commented on src/main/resources/db/migration/V202409081401__create_pet.sql
> +CREATE INDEX idx_pets_company_id ON pet(company_id);
better rename it to idx_pet_on_company_id

2024-09-10 15:10 UTC, mayhuberman approved these changes

2024-09-11 07:08 UTC, merged